# Build stage
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
COPY apps/api/package*.json ./apps/api/
RUN npm install
COPY apps/api ./apps/api
RUN npm run build --workspace=apps/api

# Production stage
FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
COPY apps/api/package*.json ./apps/api/
RUN npm prune --production
COPY --from=builder /app/apps/api/dist ./apps/api/dist
EXPOSE 5000
CMD ["node", "apps/api/dist/index.js"]
